apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-task
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
    spec:
      containers:
      - name: add-task
        env:
          - name: CONNECTION_STRING
            value: "Driver={Driver={ODBC Driver 18 for SQL Server};Server=tcp:mssqldbserverdev.database.windows.net,1433;Database=sqldbdev;Uid=sqladminuser;Pwd=Test@12345;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        image: acrtodoappdev01.azurecr.io/microtodoaddtask:11
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: acr-creds
